export const PREFIX = {
  AUTH: 'AUTH',
  APP: 'APP',
  SUPPLIERS: 'SUPPLIERS',
  SUPPLIER: 'SUPPLIER',
  PRODUCTS: 'PRODUCTS',
  PRODUCT: 'PRODUCT',
  CATEGORIES: 'CATEGORIES',
  ORDER: 'ORDER',
  CHART: 'CHART',
  ACCOUNT: 'ACCOUNT',
  API: 'API',
  STATION: 'STATION',
  STATION_PRODUCT: 'STATION_PRODUCT',
  STATION_ORDER: 'STATION_ORDER',
  PRODUCT_UNIT: 'PRODUCT_UNIT',
  REGION: 'REGION',
  ROLE: 'ROLE',
  CUSTOMER: 'CUSTOMER',

  //status API
  API_CALLING: 'API_CALLING',
  API_CALLED_SUCCESS: 'API_CALLED_SUCCESS',
  API_CALLED_FAILURE: 'API_CALLED_FAILURE',

  // bookstore
  BOOK: 'BOOK',
  CATEGORY: 'CATEGORY',
  CART: 'CART',
  AUTHOR: 'AUTHOR',
  PUBLISHER: 'PUBLISHER',
  COUPON: 'COUPON',
};

export const typesWithPrefix = (prefix) => (key) => `${prefix}_${key}`;
